directory: /media/external/Music
library: /media/external/Music/.library.blb

plugins:
    - inline
    - chroma
    - lyrics
    - fetchart
    - embedart
    - replaygain
    - scrub
    - ftintitle
    - bpm
    - mpdupdate

import:
    # move: yes
    resume: ask
    incremental: yes
    languages: ['en']

match:
    preferred:
        media: ['CD', 'Digital Media|File']
        original_year: yes

item_fields:
    mp3_bitrate: (' (%dkbps)' % (bitrate // 1000)) if format.upper() == 'MP3' else ''

paths:
    default: "$albumartist/Albums/($year) $album%aunique{catalognum label albumtype, catalognum label albumtype}/$track $title$mp3_bitrate"
    albumtype:ep: "$albumartist/EPs/($year) $album%aunique{catalognum label albumtype, catalognum label albumtype}/$track $title$mp3_bitrate"

# replace:
    # '^\.''":': _
